[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Simply Circles Purple Light Envolved
Comment=GTK Theme to use with Simply Circles Icon Theme
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Simply Circles Purple Light Envolved
GtkTheme=Simply_Circles_Purple_Light_Envolved
MetacityTheme=Simply_Circles_Purple_Light_Envolved
IconTheme=Simply-Purple-Circles
CursorTheme=DMZ-Black
ButtonLayout=:minimize,maximize,close
