[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Simply Circles Orange Light Envolved
Comment=GTK Theme to use with Simply Circles Icon Theme
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Simply Circles Orange Light Envolved
GtkTheme=Simply_Circles_Orange_Light_Envolved
MetacityTheme=Simply_Circles_Orange_Light_Envolved
IconTheme=Simply-Orange-Circles
CursorTheme=DMZ-Black
ButtonLayout=:minimize,maximize,close
